name: SessionStorage-UT

on: [push]

jobs:
  install:
    name: Install dependencies
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache node modules
        id: cache-npm
        uses: actions/cache@v4.2.3
        env:
          cache-name: cached-npm-deps
        with:
          path: ./node_modules
          key: ${{ hashFiles('./package.json') }}

      - name: Install required dependencies on cache miss (npm)
        if: steps.cache-npm.outputs.cache-hit != 'true'
        run: |
          npm install

  test:
    name: Run the unit tests
    runs-on: windows-latest
    needs: [install]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Pull the npm dependencies
        uses: actions/cache@v4.2.3
        with:
          path: ./node_modules
          key: ${{ hashFiles('./package.json') }}

      - name: Run unit tests
        run: npx jest
