name: SessionStorage-UT

on: [push]

jobs:
  install:
    name: Install dependencies
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Display tools versions
        run: npm --version;

      - name: Restore all the packages
        run: npm ci

      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: ./node_modules
          key: ${{ hashFiles('./package.json') }}


  verify:
    name: Verify the sources
    runs-on: windows-latest
    needs: install

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Cache
        uses: actions/cache@v2.1.6
        with:
          path: ./node_modules
          key: ${{ hashFiles('./package.json') }}

      - name: Run ESLint on the sources
        run: npx eslint .


  test:
    name: Run the unit tests
    runs-on: windows-latest
    needs: [verify]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2

      - name: Pull the npm dependencies
        uses: actions/cache@v2.1.6
        with:
          path: ./node_modules
          key: ${{ hashFiles('./package.json') }}

      - name: Run unit tests
        run: npx jest
